import type { Metadata } from "next";
import { Fustat, Inter, Manrope, Onest } from 'next/font/google';
import localFont from "next/font/local";
import "./globals.css";

const manropeFont = Manrope({
  variable: "--font-manrope",
  weight: ["500", "600"]
});

const degularFont = localFont({
  src: "./fonts/Degular-Semibold.woff2",
  weight: "600",
  variable: "--font-degular",
});

const interFont = Inter({
  variable: "--font-manrope",
  weight: ["400", "500", "600", "700"]
});

const onsetFont = Onest({
  variable: "--font-onest",
  weight: ["400", "500", "600", "700"]
});

const fustatFont = Fustat({
  variable: "--font-futura",
  weight: ["400", "500", "600", "700"]
});

const segoeUIFont = localFont({
  src: "./fonts/segoe-ui.woff",
  weight: "100 900",
  variable: "--font-segoe-ui",
});



export const metadata: Metadata = {
  title: "Flex Code",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${manropeFont.variable}
          ${degularFont.variable}
          ${interFont.variable}
          ${onsetFont.variable}
          ${fustatFont.variable}
          ${segoeUIFont.variable}
          antialiased
        `}
      >
        {children}
      </body>
    </html>
  );
}
